### DISCUSSION TITLE
Cards Code - Share your cards here

### DISCUSSION THREAD

**Discussion by Pieterjvr** [hawky358/hass_ids_hyyp#14] [General]
Hi @hawky358 

is it possible to share some of the dashboard cards/panel how you created them and what lovelace you used.

Regards
Pieter

**Comment by spencerw67** [comment]
For anyone interested, this is a non-alarm-panel card I created to use the integration.  The partition has two sleep modes.  The card has been optimised for viewing on a mobile phone, hence the addition of card-mod.  I also use custom:vertical-stack-in-card which allows more icons (6 in the case of another partition) to be shown in a single row.

![Screenshot 2023-07-06 175223](https://github.com/hawky358/hass_ids_hyyp/assets/73069594/806c2c86-f347-49d5-83b5-d6271831ff1f)

```
type: custom:vertical-stack-in-card
cards:
  - type: custom:vertical-stack-in-card
    card_mod:
      style: |
        ha-card {border: none}  
    cards:
      - type: custom:mushroom-title-card
        title: Partition 1 (inside)
      - type: custom:mushroom-template-card
        card_mod:
          style: |
            ha-card {border: none}
        primary: Partition 1
        secondary: '{{ states(entity) }} '
        icon: |-
          {% if states(entity) == 'Disarmed' %}
            mdi:shield-off
          {% else %}
            mdi:shield
          {% endif %}
        multiline_secondary: false
        icon_color: |-
          {% if states(entity) == 'Disarmed' %}
            disabled
          {% else %}
            green
          {% endif %}
        entity: sensor.rondebosch_partition_1_armed_status
        tap_action:
          action: more-info
        hold_action:
          action: none
        double_tap_action:
          action: none
      - square: false
        type: grid
        columns: 4
        cards:
          - type: custom:mushroom-template-card
            card_mod:
              style: |
                ha-card {border: none}
            entity: sensor.rondebosch_partition_1_armed_status
            layout: horizontal
            icon_color: |-
              {% if states(entity) == 'Armed Stay evening' %}
                green
              {% else %}
                disabled
              {% endif %}
            icon: mdi:shield-home-outline
            tap_action:
              action: call-service
              service: button.press
              target:
                entity_id: button.rondebosch_partition_1_arm_stay_evening
              data: {}
            multiline_secondary: false
            hold_action:
              action: more-info
            double_tap_action:
              action: none
          - type: custom:mushroom-template-card
            card_mod:
              style: |
                ha-card {border: none}
            entity: sensor.rondebosch_partition_1_armed_status
            layout: horizontal
            icon_color: |-
              {% if states(entity) == 'Armed Stay sleep ' %}
                green
              {% else %}
                disabled
              {% endif %}
            icon: mdi:shield-moon-outline
            tap_action:
              action: call-service
              service: button.press
              target:
                entity_id: button.rondebosch_partition_1_arm_stay_sleep
              data: {}
            multiline_secondary: false
            hold_action:
              action: more-info
            double_tap_action:
              action: none
          - type: custom:mushroom-template-card
            card_mod:
              style: |
                ha-card {border: none}
            entity: sensor.rondebosch_partition_1_armed_status
            fill_container: true
            layout: horizontal
            icon: mdi:shield-lock-outline
            icon_color: |-
              {% if states(entity) == 'Armed away' %}
                red
              {% else %}
                disabled
              {% endif %}
            tap_action:
              action: call-service
              service: alarm_control_panel.alarm_arm_away
              target:
                entity_id: alarm_control_panel.partition_1
              data: {}
            multiline_secondary: true
            hold_action:
              action: more-info
            double_tap_action:
              action: none
          - type: custom:mushroom-template-card
            card_mod:
              style: |
                ha-card {border: none}
            entity: sensor.rondebosch_partition_1_armed_status
            fill_container: true
            layout: horizontal
            icon: mdi:shield-off-outline
            icon_color: |-
              {% if states(entity) == 'Disarmed' %}
                disabled
              {% else %}
                red
              {% endif %}
            tap_action:
              action: call-service
              service: alarm_control_panel.alarm_disarm
              target:
                entity_id: alarm_control_panel.partition_1
              data: {}
            multiline_secondary: true
      - type: custom:text-divider-row
        text: Bypass
      - type: custom:vertical-stack-in-card
        horizontal: true
        card_mod:
          style: |
            ha-card {border: none}
        cards:
          - type: custom:mushroom-entity-card
            entity: switch.d_stair8_drs
            name: Doors
            primary_info: none
            secondary_info: name
            layout: vertical
            tap_action:
              action: toggle
            card_mod:
              style: |
                ha-card {
                  --card-secondary-font-size: 9px;
                  border: none}               
          - type: custom:mushroom-entity-card
            entity: switch.front_door
            name: Front
            primary_info: none
            secondary_info: name
            layout: vertical
            tap_action:
              action: toggle
            card_mod:
              style: |
                ha-card {
                  --card-secondary-font-size: 9px;
                  border: none}               
          - type: custom:mushroom-entity-card
            entity: switch.pir_gym_rm
            name: Study
            primary_info: none
            secondary_info: name
            layout: vertical
            tap_action:
              action: toggle
            card_mod:
              style: |
                ha-card {
                  --card-secondary-font-size: 9px;
                  border: none}                
          - type: custom:mushroom-entity-card
            entity: switch.pir_loungex2
            name: Lounge
            primary_info: none
            secondary_info: name
            layout: vertical
            tap_action:
              action: toggle
            card_mod:
              style: |
                ha-card {
                  --card-secondary-font-size: 9px;
                  border: none}                
          - type: custom:mushroom-entity-card
            entity: switch.pir_upstairs
            name: Upstairs
            primary_info: none
            secondary_info: name
            layout: vertical
            tap_action:
              action: toggle
            card_mod:
              style: |
                ha-card {
                  --card-secondary-font-size: 9px;
                  border: none}

```

**Reply by hawky358** [reply]
>For anyone interested, this is a non-alarm-panel card I created to use the integration.

Thanks for sharing. I've made this a pinned discussion topic so people can find something they like and also share theirs.

**Comment by hawky358** [comment]
> Hi @hawky358
> is it possible to share some of the dashboard cards/panel how you created them and what lovelace you used.
> Regards Pieter

Hey,

This is from my readme. Sized for my phone (I use the 1 stay profile one below though (See next post)

I use the following additional cards / frontends for these:

- Vertical stack in card
- Button-card by @RomRider
- decluttering-card (Not all of them are decluttered, I only started that relatively recently and haven't done these cards yet, but you can do that if you want)

![awayexample](https://github.com/hawky358/hass_ids_hyyp/assets/16265473/3649e5e9-feee-4389-9946-43f488c5173f)
![stayexample](https://github.com/hawky358/hass_ids_hyyp/assets/16265473/21d5449b-c0f5-403c-839d-95a2a120d16f)


Here's the decluttering template. I believe it's only used for the "multiple stay profiles". Just read the instructions for the card, but you just put this at the top of the "raw configuration" of the specific dashboard.

```
decluttering_templates:
  alarmStayProfileButton:
    card:
      type: custom:button-card
      tap_action:
        action: call-service
        service: button.press
        service_data:
          entity_id: '[[entity]]'
      icon: mdi:shield-home-outline
      size: 50%
      color: black
      show_state: false
      name: '[[name]]'
      styles:
        card:
          - font-size: 20px
          - color: White
          - padding-top: 0px
          - padding-bottom: 0px
          - height: 50px
          - border-radius: 0px
          - margin-top: 0px
          - margin-bottom: 0px
          - border-color: rgba(0,0,0,0)
        name:
          - color: black
          - font: bold 12px Roboto
      hold_action:
        action: none
```

Here's the actual card

```
type: custom:vertical-stack-in-card
cards:
  - type: custom:button-card
    show_label: true
    name: Binne
    icon: |
      [[[
        if (states["sensor.huis_binne_armed_status"].state == "Disarmed") return 'mdi:lock-open-outline';
        else return 'mdi:lock-outline';
      ]]] 
    label: |
      [[[
        return states["sensor.huis_binne_armed_status"].state
      ]]] 
    styles:
      card:
        - background-color: |
            [[[
              if (states["sensor.huis_binne_armed_status"].state == "Disarmed") return 'Green';
              else return 'red';
            ]]]
        - font-size: 30px
        - color: White
        - padding-top: 0px
        - padding-bottom: 0px
      label:
        - color: White
        - font-size: 15px
      icon:
        - color: White
        - width: 30px
  - type: conditional
    conditions:
      - entity: alarm_control_panel.binne
        state: armed_away
    card:
      type: custom:button-card
      tap_action:
        action: call-service
        service: alarm_control_panel.alarm_disarm
        service_data:
          entity_id: alarm_control_panel.binne
      icon: mdi:shield-lock-open-outline
      color: black
      show_state: false
      name: Disarm Binne
      styles:
        card:
          - font-size: 30px
          - color: White
          - padding-top: 0px
          - padding-bottom: 0px
          - height: 100px
          - border-radius: 0px
          - border-color: rgba(0,0,0,0)
        name:
          - color: black
          - font: bold 12px Roboto
      hold_action:
        action: none
  - type: conditional
    conditions:
      - entity: alarm_control_panel.binne
        state: disarmed
    card:
      type: horizontal-stack
      cards:
        - type: custom:button-card
          tap_action:
            action: call-service
            service: alarm_control_panel.alarm_arm_away
            service_data:
              entity_id: alarm_control_panel.binne
          icon: mdi:shield-lock-outline
          color: black
          show_state: false
          name: Away Arm
          styles:
            card:
              - font-size: 30px
              - color: White
              - padding-top: 0px
              - padding-bottom: 0px
              - height: 100px
              - border-radius: 0px
              - border-color: rgba(0,0,0,0)
            name:
              - color: black
              - font: bold 12px Roboto
          hold_action:
            action: none
        - type: vertical-stack
          cards:
            - type: horizontal-stack
              cards:
                - type: vertical-stack
                  cards:
                    - type: custom:decluttering-card
                      template: alarmStayProfileButton
                      variables:
                        - name: Stay Arm 1
                        - entity: button.huis_binne_arm_stay_1
                    - type: custom:decluttering-card
                      template: alarmStayProfileButton
                      variables:
                        - name: Stay Arm 3
                        - entity: button.huis_binne_arm_stay_3
                - type: vertical-stack
                  cards:
                    - type: custom:decluttering-card
                      template: alarmStayProfileButton
                      variables:
                        - name: Stay Arm 2
                        - entity: button.huis_binne_arm_stay_2
                    - type: custom:decluttering-card
                      template: alarmStayProfileButton
                      variables:
                        - name: Stay Arm 4
                        - entity: button.huis_binne_arm_stay_4
  - type: conditional
    conditions:
      - entity: alarm_control_panel.binne
        state_not: disarmed
      - entity: alarm_control_panel.binne
        state_not: armed_away
    card:
      type: horizontal-stack
      cards:
        - type: custom:button-card
          tap_action:
            action: call-service
            service: alarm_control_panel.alarm_disarm
            service_data:
              entity_id: alarm_control_panel.binne
          icon: mdi:shield-lock-open-outline
          color: black
          show_state: false
          name: Disarm Binne
          styles:
            card:
              - font-size: 30px
              - color: White
              - padding-top: 0px
              - padding-bottom: 0px
              - height: 100px
              - border-radius: 0px
              - border-color: rgba(0,0,0,0)
            name:
              - color: black
              - font: bold 12px Roboto
          hold_action:
            action: none
        - type: vertical-stack
          cards:
            - type: horizontal-stack
              cards:
                - type: vertical-stack
                  cards:
                    - type: custom:decluttering-card
                      template: alarmStayProfileButton
                      variables:
                        - name: Stay Arm 1
                        - entity: button.huis_binne_arm_stay_1
                    - type: custom:decluttering-card
                      template: alarmStayProfileButton
                      variables:
                        - name: Stay Arm 3
                        - entity: button.huis_binne_arm_stay_3
                - type: vertical-stack
                  cards:
                    - type: custom:decluttering-card
                      template: alarmStayProfileButton
                      variables:
                        - name: Stay Arm 2
                        - entity: button.huis_binne_arm_stay_2
                    - type: custom:decluttering-card
                      template: alarmStayProfileButton
                      variables:
                        - name: Stay Arm 4
                        - entity: button.huis_binne_arm_stay_4
```

**Comment by hawky358** [comment]
Here's the code for a single stay profile card. Basically the same just modified the final part

![image](https://github.com/hawky358/hass_ids_hyyp/assets/16265473/a467caa7-09e3-4b23-916f-454fc7b2d9b2)


```
type: custom:vertical-stack-in-card
cards:
  - type: custom:button-card
    show_label: true
    name: Binne
    icon: |
      [[[
        if (states["sensor.huis_binne_armed_status"].state == "Disarmed") return 'mdi:lock-open-outline';
        else return 'mdi:lock-outline';
      ]]] 
    label: |
      [[[
        return states["sensor.huis_binne_armed_status"].state
      ]]] 
    styles:
      card:
        - background-color: |
            [[[
              if (states["sensor.huis_binne_armed_status"].state == "Disarmed") return 'Green';
              else return 'red';
            ]]]
        - font-size: 30px
        - color: White
        - padding-top: 0px
        - padding-bottom: 0px
      label:
        - color: White
        - font-size: 15px
      icon:
        - color: White
        - width: 30px
  - type: conditional
    conditions:
      - entity: alarm_control_panel.binne
        state: disarmed
    card:
      type: horizontal-stack
      cards:
        - type: custom:button-card
          tap_action:
            action: call-service
            service: alarm_control_panel.alarm_arm_away
            service_data:
              entity_id: alarm_control_panel.binne
          icon: mdi:shield-lock-outline
          color: black
          show_state: false
          name: Away Arm
          styles:
            card:
              - font-size: 30px
              - color: White
              - padding-top: 0px
              - padding-bottom: 0px
              - height: 100px
              - border-radius: 0px
              - border-color: rgba(0,0,0,0)
            name:
              - color: black
              - font: bold 12px Roboto
          hold_action:
            action: none
        - type: custom:button-card
          tap_action:
            action: call-service
            service: alarm_control_panel.alarm_arm_home
            service_data:
              entity_id: alarm_control_panel.binne
          icon: mdi:shield-home-outline
          color: black
          show_state: false
          name: Stay Arm
          styles:
            card:
              - font-size: 30px
              - color: White
              - padding-top: 0px
              - padding-bottom: 0px
              - height: 100px
              - border-radius: 0px
              - border-color: rgba(0,0,0,0)
            name:
              - color: black
              - font: bold 12px Roboto
          hold_action:
            action: none
  - type: conditional
    conditions:
      - entity: alarm_control_panel.binne
        state_not: disarmed
    card:
      type: custom:button-card
      tap_action:
        action: call-service
        service: alarm_control_panel.alarm_disarm
        service_data:
          entity_id: alarm_control_panel.binne
      icon: mdi:shield-lock-open-outline
      color: black
      show_state: false
      name: Disarm Binne
      styles:
        card:
          - font-size: 30px
          - color: White
          - padding-top: 0px
          - padding-bottom: 0px
          - height: 100px
          - border-radius: 0px
          - border-color: rgba(0,0,0,0)
        name:
          - color: black
          - font: bold 12px Roboto
      hold_action:
        action: none
```
